FROM apache/airflow:2.10.0-python3.11
USER root
RUN apt-get update && apt-get install -y docker.io git ssh && apt-get clean
RUN usermod -aG root,sudo airflow
USER airflow
COPY requirements/airflow-requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt