FROM apache/airflow:2.10.0-python3.11
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless git ssh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
COPY requirements/airflow-requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt