FROM python:3.11-slim
RUN apt-get update && apt-get install -y openjdk-17-jre-headless git ssh && apt-get clean
WORKDIR /app
COPY requirements/mlcode-requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
COPY src/ /app/src/