FROM python:3.11-slim
WORKDIR /app
COPY requirements/api-requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY src/api /app/api
EXPOSE 5910
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5910"]