windows:
  data_dir: "data"

linux:
  data_dir: "/storage/data/datasets/team23_dataset"

dataset:
  filename: "WA_Fn-UseC_-Telco-Customer-Churn.csv"

processed:
  directory: "processed"
  train: "train"
  test: "test"